"""Generate an in-memory Purchase Order PDF with fpdf2 + HarfBuzz shaping.

Page 1 = the order (supplier-facing copy). Page 2 = internal approval trail.
Pass supplier_copy=True to produce page 1 only (a clean copy for the supplier).
Uses the bundled Battambang font (Khmer + Latin) so Khmer names render correctly.
"""
import logging
import os
import urllib.request
from io import BytesIO

from fpdf import FPDF
from fpdf.fonts import FontFace

from config import Config
import flow as _flow

FONT_PATH = os.path.join(os.path.dirname(__file__), "fonts", "Battambang.ttf")
FONT_BOLD_PATH = os.path.join(os.path.dirname(__file__), "fonts", "Battambang-Bold.ttf")
FONT = "Battambang"

# Fallback download (Google Fonts) if the fonts weren't committed to the repo.
_FONT_BASE = "https://raw.githubusercontent.com/google/fonts/main/ofl/battambang"
FONT_URLS = {
    FONT_PATH: f"{_FONT_BASE}/Battambang-Regular.ttf",
    FONT_BOLD_PATH: f"{_FONT_BASE}/Battambang-Bold.ttf",
}


def ensure_fonts():
    """Download the bundled fonts if missing (so deployment doesn't require uploading them)."""
    try:
        os.makedirs(os.path.dirname(FONT_PATH), exist_ok=True)
    except Exception:
        pass
    for path, url in FONT_URLS.items():
        try:
            if not os.path.exists(path) or os.path.getsize(path) < 1000:
                logging.getLogger("po_bot").info("Fetching font %s", os.path.basename(path))
                urllib.request.urlretrieve(url, path)
        except Exception as e:
            logging.getLogger("po_bot").warning("Could not fetch font %s: %s", os.path.basename(path), e)

TEAL = (24, 123, 133)
ORANGE = (198, 125, 31)
GREY = (90, 90, 90)
WHITE = (255, 255, 255)

STAGE_LABEL = {
    "stock": "Stock controller", "book": "Bookkeeping", "fin": "Finance manager",
    "gm": "General manager", "board": "Board of director",
    "approved": "Approved", "returned": "Returned to requester",
}
# There is no ordering gate -- nobody taps "Ordered", and no ordering_by /
# ordering_at column exists to fill. Listing it here printed a permanent
# "Ordering: Pending" line on every approval copy, including closed POs, which
# reads as a step someone forgot rather than a step that does not exist.
STAGES = [
    ("Stock controller", "stock"),
    ("Bookkeeping", "book"),
    ("Finance manager", "fin"),
    ("General manager", "gm"),
    ("Board of director", "board"),
]


def _money(v):
    try:
        return f"{Config.CURRENCY}{float(v):,.2f}"
    except (TypeError, ValueError):
        return f"{Config.CURRENCY}{v}"


def _is_urgent(po):
    return str(po.get("urgent", "")).strip().lower() in ("yes", "true", "1")


def _approval_rows(po):
    rows = []
    stage = po.get("stage")
    reject_stage = po.get("reject_stage")
    reject_reason = po.get("reject_reason")
    for label, code in STAGES:
        by = str(po.get(f"{code}_by", "")).strip()
        at = str(po.get(f"{code}_at", "")).strip()
        if by:
            verb = {"stock": "Checked", "book": "Booked"}.get(code, "Approved")
            status = f"{verb} by {by}" + (f"  -  {at}" if at else "")
        elif reject_stage == code and reject_reason:
            status = f"Rejected: {reject_reason}"
        elif stage == code:
            status = ">> Awaiting"
        elif _is_urgent(po) and code in ("gm", "board"):
            status = "Notified only (no approval)"
        else:
            status = "Pending"
        rows.append((label, status))
    return rows


def generate_po_pdf(po, items, supplier_copy=False, show_prices=True):
    """show_prices=False renders a price-blind PDF (No/Code/Item/Pack/Qty only, no totals,
    no price-change note) — used for the Stock controller stage. The supplier copy always
    includes prices (it is the order document)."""
    ensure_fonts()
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(16, 16, 16)
    pdf.set_auto_page_break(True, margin=16)
    pdf.add_font(FONT, "", FONT_PATH)
    pdf.add_font(FONT, "B", FONT_BOLD_PATH)
    headings = FontFace(fill_color=TEAL, color=WHITE)
    bold = FontFace(emphasis="BOLD")

    def header(subtitle, sub_color):
        pdf.set_font(FONT, "", 20)
        pdf.set_text_color(*TEAL)
        pdf.cell(0, 10, Config.COMPANY_NAME, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(FONT, "", 11)
        pdf.set_text_color(*sub_color)
        pdf.cell(0, 7, subtitle, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    def meta(label, value):
        pdf.set_font(FONT, "", 11)
        pdf.set_text_color(*GREY)
        pdf.cell(34, 7, label, new_x="RIGHT", new_y="TOP")
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    def footer(note=""):
        pdf.ln(8)
        pdf.set_font(FONT, "", 8)
        pdf.set_text_color(150, 150, 150)
        txt = "Generated by CML PO Bot" + (f"   -   {note}" if note else "")
        pdf.cell(0, 5, txt, new_x="LMARGIN", new_y="NEXT")

    # ---------- PAGE 1: the order (supplier-facing) ----------
    pdf.add_page()
    pdf.set_text_shaping(True)
    header("Purchase Order", ORANGE)
    meta("PO No.", po.get("po_no"))
    meta("Date", po.get("created_at", ""))
    meta("Supplier", po.get("supplier", ""))
    if str(po.get("category", "")).strip():
        meta("Category", po.get("category", ""))
    pdf.ln(4)

    if supplier_copy:
        # The supplier's own code and their own item name. The internal CML
        # code means nothing to them -- and their code is not always unique
        # (two products can share one), so the name disambiguates the line.
        with pdf.table(
            width=178,
            col_widths=(9, 30, 68, 20, 11, 20, 20),
            text_align=("CENTER", "LEFT", "LEFT", "LEFT", "RIGHT", "RIGHT", "RIGHT"),
            headings_style=headings,
            line_height=7,
            first_row_as_headings=True,
        ) as table:
            head = table.row()
            for h in ["No", "Supplier code", "Item", "Pack", "Qty",
                      "Unit price", "Total"]:
                head.cell(h)
            for i, it in enumerate(items, 1):
                r = table.row()
                r.cell(str(i))
                r.cell(str(it.get("supplier_code", "")))
                r.cell(str(it.get("supplier_reagent") or it.get("item", "")))
                r.cell(str(it.get("pack", "")))
                r.cell(str(it.get("qty", "")))
                r.cell(_money(it.get("unit_price", 0)))
                r.cell(_money(it.get("line_total", 0)))
            tot = table.row()
            for _ in range(5):
                tot.cell("")
            tot.cell("Total", style=bold)
            tot.cell(_money(po.get("total", 0)), style=bold)
        footer("Supplier copy")
        return BytesIO(bytes(pdf.output()))

    if show_prices:
        with pdf.table(
            width=178,
            col_widths=(8, 27, 50, 28, 10, 13, 22, 20),
            text_align=("CENTER", "LEFT", "LEFT", "LEFT", "RIGHT",
                        "RIGHT", "RIGHT", "RIGHT"),
            headings_style=headings,
            line_height=7,
            first_row_as_headings=True,
        ) as table:
            head = table.row()
            # No supplier code here. It is the supplier's own reference and
            # means nothing to an approver -- it belongs on the copy that is
            # actually sent out. The ordering group keeps that copy, so the
            # mapping from a delivery note back to a line is not lost. The
            # width it frees goes to the item name, which is what an approver
            # is actually reading.
            for h in ["No", "CML code", "Item", "Pack", "Qty",
                      "Stock", "Unit price", "Total"]:
                head.cell(h)
            for i, it in enumerate(items, 1):
                r = table.row()
                r.cell(str(i))
                r.cell(str(it.get("material_code", "")))
                r.cell(str(it.get("item", "")))
                r.cell(str(it.get("pack", "")))
                r.cell(str(it.get("qty", "")))
                # The stock count exists so Finance, GM and the Board can judge
                # whether the quantity is reasonable -- it has to appear on
                # THEIR copy, not only the stock controller's.
                r.cell(str(it.get("on_hand", "") or "-"))
                d = _flow.price_drift(it)
                price = _money(it.get("unit_price", 0))
                if d:
                    ref, _u, pct, flagged = d
                    price += (f"\n(was {_money(ref)}"
                              + (f", {pct:+.0f}%" if pct is not None else "")
                              + (" <<" if flagged else "") + ")")
                r.cell(price)
                r.cell(_money(it.get("line_total", 0)))
            tot = table.row()
            for _ in range(6):
                tot.cell("")
            tot.cell("Total", style=bold)
            tot.cell(_money(po.get("total", 0)), style=bold)
        if any(_flow.price_drift(it) for it in items):
            pdf.ln(2)
            pdf.set_font(FONT, "", 9)
            pdf.set_text_color(*ORANGE)
            pdf.cell(0, 5,
                     "Prices marked (was ...) were confirmed with the supplier "
                     "and differ from the master list;  <<  marks a change of "
                     f"+/-{Config.OTHER_PRICE_TOLERANCE_PCT:.0f}% or more.",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
    else:
        with pdf.table(
            width=178,
            col_widths=(12, 28, 74, 26, 18, 20),
            text_align=("CENTER", "LEFT", "LEFT", "LEFT", "RIGHT", "RIGHT"),
            headings_style=headings,
            line_height=7,
            first_row_as_headings=True,
        ) as table:
            head = table.row()
            for h in ["No", "Code", "Item", "Pack", "Qty", "On hand"]:
                head.cell(h)
            for i, it in enumerate(items, 1):
                r = table.row()
                r.cell(str(i))
                r.cell(str(it.get("material_code", "")))
                r.cell(str(it.get("item", "")))
                r.cell(str(it.get("pack", "")))
                r.cell(str(it.get("qty", "")))
                r.cell(str(it.get("on_hand", "") or "-"))

    # ---------- PAGE 2: approval (internal) ----------
    pdf.add_page()
    header("Purchase Order Approval", TEAL)
    meta("PO No.", po.get("po_no"))
    meta("Supplier", po.get("supplier", ""))
    meta("Date", po.get("created_at", ""))
    meta("Urgent", "Yes" if _is_urgent(po) else "No")
    if str(po.get("payment_type", "")).strip():
        meta("Payment", po.get("payment_type", ""))
    meta("Current stage", STAGE_LABEL.get(po.get("stage"), po.get("stage", "")))
    if str(po.get("order_due", "")).strip():
        meta("Send to supplier", po.get("order_due", ""))
    if str(po.get("reason", "")).strip():
        pdf.set_font(FONT, "", 11)
        pdf.set_text_color(*GREY)
        pdf.cell(0, 7, "Reason:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 6, str(po.get("reason", "")), new_x="LMARGIN", new_y="NEXT")

    # Flag reference-price changes for approvers (internal page only, never the supplier copy,
    # and not on the price-blind Stock controller copy).
    # Requester's justification for the supplier chosen for the whole PO. The
    # supplier is picked once, before any item is seen, so this is PO-level.
    if show_prices and str(po.get("supplier_reason", "")).strip():
        pdf.ln(2)
        pdf.set_font(FONT, "", 11)
        pdf.set_text_color(*ORANGE)
        pdf.cell(0, 7, "Supplier choice (a cheaper supplier existed):",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 6, "  -  " + str(po.get("supplier_reason", "")),
                       new_x="LMARGIN", new_y="NEXT")

    # Per-line remarks typed in the template's Note column.
    if show_prices:
        sel_notes = [f"{it.get('item', '')}: {str(it.get('variant_reason', '')).strip()}"
                     for it in items if str(it.get("variant_reason", "")).strip()]
        if sel_notes:
            pdf.ln(2)
            pdf.set_font(FONT, "", 11)
            pdf.set_text_color(*ORANGE)
            pdf.cell(0, 7, "Line notes from the request file:",
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
            for note in sel_notes:
                pdf.multi_cell(0, 6, "  -  " + note, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    with pdf.table(
        width=178,
        col_widths=(52, 126),
        text_align=("LEFT", "LEFT"),
        headings_style=headings,
        line_height=7,
        first_row_as_headings=True,
    ) as table:
        head = table.row()
        head.cell("Stage")
        head.cell("Status")
        rr = table.row()
        rr.cell("Requester")
        _created = str(po.get("created_at", "")).strip()
        rr.cell(str(po.get("requester_name", "")) + (f"  -  {_created}" if _created else ""))
        for label, status in _approval_rows(po):
            r = table.row()
            r.cell(label)
            r.cell(status)

    footer()
    return BytesIO(bytes(pdf.output()))
