"""Generate an in-memory Purchase Order PDF with fpdf2 + HarfBuzz shaping.

Page 1 = the order (supplier-facing copy). Page 2 = internal approval trail.
Pass supplier_copy=True to produce page 1 only (a clean copy for the supplier).
Uses the bundled Battambang font (Khmer + Latin) so Khmer names render correctly.
"""
import logging
import os
import urllib.request
from io import BytesIO

from fpdf import FPDF
from fpdf.fonts import FontFace

from config import Config

FONT_PATH = os.path.join(os.path.dirname(__file__), "fonts", "Battambang.ttf")
FONT_BOLD_PATH = os.path.join(os.path.dirname(__file__), "fonts", "Battambang-Bold.ttf")
FONT = "Battambang"

# Fallback download (Google Fonts) if the fonts weren't committed to the repo.
_FONT_BASE = "https://raw.githubusercontent.com/google/fonts/main/ofl/battambang"
FONT_URLS = {
    FONT_PATH: f"{_FONT_BASE}/Battambang-Regular.ttf",
    FONT_BOLD_PATH: f"{_FONT_BASE}/Battambang-Bold.ttf",
}


def ensure_fonts():
    """Download the bundled fonts if missing (so deployment doesn't require uploading them)."""
    try:
        os.makedirs(os.path.dirname(FONT_PATH), exist_ok=True)
    except Exception:
        pass
    for path, url in FONT_URLS.items():
        try:
            if not os.path.exists(path) or os.path.getsize(path) < 1000:
                logging.getLogger("po_bot").info("Fetching font %s", os.path.basename(path))
                urllib.request.urlretrieve(url, path)
        except Exception as e:
            logging.getLogger("po_bot").warning("Could not fetch font %s: %s", os.path.basename(path), e)

TEAL = (24, 123, 133)
ORANGE = (198, 125, 31)
GREY = (90, 90, 90)
WHITE = (255, 255, 255)

STAGE_LABEL = {
    "stock": "Stock controller", "book": "Bookkeeping", "fin": "Finance manager",
    "gm": "General manager", "board": "Board of director",
    "approved": "Approved", "returned": "Returned to requester",
}
STAGES = [
    ("Stock controller", "stock"),
    ("Bookkeeping", "book"),
    ("Finance manager", "fin"),
    ("General manager", "gm"),
    ("Board of director", "board"),
]


def _money(v):
    try:
        return f"{Config.CURRENCY}{float(v):,.2f}"
    except (TypeError, ValueError):
        return f"{Config.CURRENCY}{v}"


def _is_urgent(po):
    return str(po.get("urgent", "")).strip().lower() in ("yes", "true", "1")


def _approval_rows(po):
    rows = []
    stage = po.get("stage")
    reject_stage = po.get("reject_stage")
    reject_reason = po.get("reject_reason")
    for label, code in STAGES:
        by = str(po.get(f"{code}_by", "")).strip()
        at = str(po.get(f"{code}_at", "")).strip()
        if by:
            verb = "Booked" if code == "book" else "Approved"
            status = f"{verb} by {by}" + (f"  -  {at}" if at else "")
        elif reject_stage == code and reject_reason:
            status = f"Rejected: {reject_reason}"
        elif stage == code:
            status = ">> Awaiting"
        elif _is_urgent(po) and code in ("gm", "board"):
            status = "Notified only (no approval)"
        else:
            status = "Pending"
        rows.append((label, status))
    return rows


def generate_po_pdf(po, items, supplier_copy=False):
    ensure_fonts()
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(16, 16, 16)
    pdf.set_auto_page_break(True, margin=16)
    pdf.add_font(FONT, "", FONT_PATH)
    pdf.add_font(FONT, "B", FONT_BOLD_PATH)
    headings = FontFace(fill_color=TEAL, color=WHITE)
    bold = FontFace(emphasis="BOLD")

    def header(subtitle, sub_color):
        pdf.set_font(FONT, "", 20)
        pdf.set_text_color(*TEAL)
        pdf.cell(0, 10, Config.COMPANY_NAME, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(FONT, "", 11)
        pdf.set_text_color(*sub_color)
        pdf.cell(0, 7, subtitle, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    def meta(label, value):
        pdf.set_font(FONT, "", 11)
        pdf.set_text_color(*GREY)
        pdf.cell(34, 7, label, new_x="RIGHT", new_y="TOP")
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    def footer(note=""):
        pdf.ln(8)
        pdf.set_font(FONT, "", 8)
        pdf.set_text_color(150, 150, 150)
        txt = "Generated by CML PO Bot" + (f"   -   {note}" if note else "")
        pdf.cell(0, 5, txt, new_x="LMARGIN", new_y="NEXT")

    # ---------- PAGE 1: the order (supplier-facing) ----------
    pdf.add_page()
    pdf.set_text_shaping(True)
    header("Purchase Order", ORANGE)
    meta("PO No.", po.get("po_no"))
    meta("Date", po.get("created_at", ""))
    meta("Supplier", po.get("supplier", ""))
    if str(po.get("category", "")).strip():
        meta("Category", po.get("category", ""))
    meta("Requester", po.get("requester_name", ""))
    meta("Urgent", "Yes" if _is_urgent(po) else "No")
    pdf.ln(4)

    with pdf.table(
        width=178,
        col_widths=(9, 22, 59, 20, 11, 28, 29),
        text_align=("CENTER", "LEFT", "LEFT", "LEFT", "RIGHT", "RIGHT", "RIGHT"),
        headings_style=headings,
        line_height=7,
        first_row_as_headings=True,
    ) as table:
        head = table.row()
        for h in ["No", "Code", "Item", "Pack", "Qty", "Unit price", "Total"]:
            head.cell(h)
        for i, it in enumerate(items, 1):
            r = table.row()
            r.cell(str(i))
            r.cell(str(it.get("material_code", "")))
            r.cell(str(it.get("item", "")))
            r.cell(str(it.get("pack", "")))
            r.cell(str(it.get("qty", "")))
            r.cell(_money(it.get("unit_price", 0)))
            r.cell(_money(it.get("line_total", 0)))
        tot = table.row()
        for _ in range(5):
            tot.cell("")
        tot.cell("Total", style=bold)
        tot.cell(_money(po.get("total", 0)), style=bold)

    if supplier_copy:
        footer("Supplier copy")
        return BytesIO(bytes(pdf.output()))

    # ---------- PAGE 2: approval (internal) ----------
    pdf.add_page()
    header("Purchase Order Approval", TEAL)
    meta("PO No.", po.get("po_no"))
    meta("Supplier", po.get("supplier", ""))
    meta("Date", po.get("created_at", ""))
    meta("Current stage", STAGE_LABEL.get(po.get("stage"), po.get("stage", "")))
    if str(po.get("reason", "")).strip():
        pdf.set_font(FONT, "", 11)
        pdf.set_text_color(*GREY)
        pdf.cell(0, 7, "Reason:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 6, str(po.get("reason", "")), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    with pdf.table(
        width=178,
        col_widths=(52, 126),
        text_align=("LEFT", "LEFT"),
        headings_style=headings,
        line_height=7,
        first_row_as_headings=True,
    ) as table:
        head = table.row()
        head.cell("Stage")
        head.cell("Status")
        for label, status in _approval_rows(po):
            r = table.row()
            r.cell(label)
            r.cell(status)

    footer()
    return BytesIO(bytes(pdf.output()))
