"""Generate an in-memory Purchase Order PDF with reportlab (CML brand colors)."""
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer

from config import Config

TEAL = colors.HexColor("#187B85")
ORANGE = colors.HexColor("#C67D1F")
GREY = colors.HexColor("#BBBBBB")


def _money(v):
    try:
        return f"{Config.CURRENCY}{float(v):,.2f}"
    except (TypeError, ValueError):
        return f"{Config.CURRENCY}{v}"


def generate_po_pdf(po, items):
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=18 * mm, bottomMargin=18 * mm,
        leftMargin=16 * mm, rightMargin=16 * mm,
        title=f"PO {po.get('po_no')}",
    )
    styles = getSampleStyleSheet()
    h_company = ParagraphStyle("company", parent=styles["Title"], textColor=TEAL, fontSize=20, spaceAfter=2)
    h_sub = ParagraphStyle("sub", parent=styles["Normal"], textColor=ORANGE, fontSize=10, spaceAfter=10)
    normal = styles["Normal"]
    right = ParagraphStyle("right", parent=normal, alignment=2)
    foot = ParagraphStyle("foot", parent=normal, fontSize=8, textColor=colors.grey)

    urgent = str(po.get("urgent", "")).strip().lower() in ("yes", "true", "1")

    elems = [
        Paragraph(Config.COMPANY_NAME, h_company),
        Paragraph("Purchase Order", h_sub),
    ]

    meta = [
        [Paragraph(f"<b>PO No.</b>  {po.get('po_no')}", normal),
         Paragraph(f"<b>Date</b>  {po.get('created_at', '')}", right)],
        [Paragraph(f"<b>Requester</b>  {po.get('requester_name', '')}", normal),
         Paragraph(f"<b>Urgent</b>  {'Yes' if urgent else 'No'}", right)],
        [Paragraph(f"<b>Supplier</b>  {po.get('supplier', '')}", normal), Paragraph("", right)],
    ]
    mt = Table(meta, colWidths=[95 * mm, 75 * mm])
    mt.setStyle(TableStyle([("BOTTOMPADDING", (0, 0), (-1, -1), 4), ("TOPPADDING", (0, 0), (-1, -1), 2)]))
    elems += [mt, Spacer(1, 8 * mm)]

    data = [["No", "Item", "Pack", "Qty", "Unit price", "Total"]]
    for i, it in enumerate(items, 1):
        data.append([str(i), it["item"], it.get("pack", ""), str(it["qty"]),
                     _money(it["unit_price"]), _money(it["line_total"])])
    data.append(["", "", "", "", "Total", _money(po.get("total", 0))])

    tbl = Table(data, colWidths=[10 * mm, 70 * mm, 24 * mm, 13 * mm, 27 * mm, 26 * mm], repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TEAL),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (3, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -2), 0.5, GREY),
        ("LINEABOVE", (0, -1), (-1, -1), 0.75, TEAL),
        ("FONTNAME", (-2, -1), (-1, -1), "Helvetica-Bold"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    elems += [tbl, Spacer(1, 14 * mm), Paragraph("Generated by CML PO Bot", foot)]

    doc.build(elems)
    buf.seek(0)
    return buf
